#ifndef __EVENT_TYPES_H__
#define __EVENT_TYPES_H__

namespace sand {

enum class EventType {

    ENTITY_ADDED,
    ENTITY_REMOVED,
    ENTITY_SIGNATURE_CHANGED,

    NETWORK_ENTITY_ADDED,
    NETWORK_ENTITY_REMOVED,

    COMPONENT_ADDED,
    COMPONENT_REMOVED,
    COMPONENT_MEMBER_CHANGED,

    PLAYER_ADDED,
    PLAYER_READDED,
    PLAYER_REMOVED,

    PLAYER_ENTITY_ADDED,

    HEALTH_EMPTIED,

    CONNECT_SOCKETS,
    SOCKETS_CONNECTED,

    TRY_CONNECT,
    CONNECT_SUCCESSFUL,
    CONNECT_FAILED,

#ifdef _CLIENT
    CHECK_CONNECT,

    SEND_HELLO,
    SEND_REHELLO,

    WELCOME_RECEIVED,
    UNWELCOME_RECEIVED,
    REWELCOME_RECEIVED,
    PLAY_RECEIVED,
    RESULTS_RECEIVED,

    DISCONNECT_SOCKETS,
#elif defined(_SERVER)
    HELLO_RECEIVED,
    REHELLO_RECEIVED,

    SEND_WELCOME,
    SEND_REWELCOME,
    SEND_PLAY,
    SEND_RESULTS,
#endif

    SEND_BYE,

    COUNT
};
}

#endif
